language: node_js
node_js:
  - "0.10"
script:
  - "npm run build && npm test"
after_script:
  - "istanbul cover --verbose --dir coverage tests/tests.js && cat coverage/lcov.info | coveralls; rm -rf coverage/lcov*"
